name: tf-checks
on:
  push:
    branches: [ feat/dynamic-users ]
  pull_request:
  workflow_dispatch:
jobs:
  _example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@feat/dynamic-users
    with:
      working_directory: './_example/'
